// Verb data, tense metadata, and sentence templates for Verbario


const PERSONS = ["yo","tú","él / ella / usted","nosotros/as","vosotros/as","ellos / ellas / ustedes"];
const PRONOUN_WORD = ["yo","tú","él","nosotros","vosotros","ellos"];

const TENSES = {
  presente:            {label:"Presente",                level:1, order:1},
  preteritoIndefinido:  {label:"Pretérito indefinido",     level:1, order:2},
  preteritoImperfecto:  {label:"Pretérito imperfecto",     level:3, order:3},
  futuro:               {label:"Futuro",                  level:3, order:4},
  condicional:          {label:"Condicional",             level:4, order:5},
  presenteSubjuntivo:    {label:"Presente de subjuntivo",   level:4, order:6},
  imperfectoSubjuntivo:  {label:"Imperfecto de subjuntivo", level:5, order:7},
};

const REGULAR_ENDINGS = {
  presente:            {ar:['o','as','a','amos','áis','an'], er:['o','es','e','emos','éis','en'], ir:['o','es','e','imos','ís','en']},
  preteritoIndefinido: {ar:['é','aste','ó','amos','asteis','aron'], er:['í','iste','ió','imos','isteis','ieron'], ir:['í','iste','ió','imos','isteis','ieron']},
  preteritoImperfecto: {ar:['aba','abas','aba','ábamos','abais','aban'], er:['ía','ías','ía','íamos','íais','ían'], ir:['ía','ías','ía','íamos','íais','ían']},
  presenteSubjuntivo:  {ar:['e','es','e','emos','éis','en'], er:['a','as','a','amos','áis','an'], ir:['a','as','a','amos','áis','an']},
};
const FUTURO_END = ['é','ás','á','emos','éis','án'];
const CONDICIONAL_END = ['ía','ías','ía','íamos','íais','ían'];

function family(inf){ return inf.endsWith('ar') ? 'ar' : inf.endsWith('er') ? 'er' : 'ir'; }
function stem(inf){ return inf.slice(0,-2); }

// Sentence templates per tense — {pronoun} gets replaced, verb shown separately as infinitive above the blank.
const TEMPLATES = {
  presente: [
    "Normalmente, {pronoun} ___ los fines de semana.",
    "Todos los días, {pronoun} ___ antes de las nueve.",
    "Mi familia dice que {pronoun} ___ demasiado rápido.",
    "Los lunes, {pronoun} ___ con el equipo de trabajo."
  ],
  preteritoIndefinido: [
    "Ayer, {pronoun} ___ sin pensarlo dos veces.",
    "El año pasado, {pronoun} ___ por primera vez.",
    "Anoche, {pronoun} ___ hasta muy tarde.",
    "De repente, {pronoun} ___ delante de todos."
  ],
  preteritoImperfecto: [
    "Cuando era más joven, {pronoun} ___ todos los veranos.",
    "Antes, {pronoun} siempre ___ los domingos por la tarde.",
    "Mientras vivía en el pueblo, {pronoun} ___ cada mañana.",
    "En aquella época, {pronoun} ___ sin ninguna prisa."
  ],
  futuro: [
    "Mañana, {pronoun} ___ en cuanto llegue a casa.",
    "El próximo año, {pronoun} ___ con más tiempo libre.",
    "Pronto, {pronoun} ___ los resultados del proyecto.",
    "Cuando termine el curso, {pronoun} ___ por fin."
  ],
  condicional: [
    "En esa situación, {pronoun} ___ de otra manera.",
    "Con más dinero, {pronoun} ___ sin dudarlo.",
    "Me dijo que {pronoun} ___ si tuviera la oportunidad.",
    "Idealmente, {pronoun} ___ antes del viernes."
  ],
  presenteSubjuntivo: [
    "Espero que {pronoun} ___ a tiempo mañana.",
    "Es importante que {pronoun} ___ con cuidado.",
    "Ojalá que {pronoun} ___ pronto buenas noticias.",
    "No creo que {pronoun} ___ antes del lunes."
  ],
  imperfectoSubjuntivo: [
    "Si {pronoun} ___ más tiempo, todo sería distinto.",
    "Ella quería que {pronoun} ___ antes de las ocho.",
    "Era imposible que {pronoun} ___ sin ayuda.",
    "Actuaba como si {pronoun} ___ la respuesta."
  ],
};

// Full verb bank. presente / preteritoIndefinido / preteritoImperfecto / presenteSubjuntivo are stored
// explicitly (safest for irregulars). futuro/condicional are derived from futuroStem.
// imperfectoSubjuntivo is derived programmatically from preteritoIndefinido (ellos form).
const VERBS = [
  {inf:"hablar", meaning:"to speak", level:1, pattern:"regular -ar", affects:[],
    presente:["hablo","hablas","habla","hablamos","habláis","hablan"],
    preteritoIndefinido:["hablé","hablaste","habló","hablamos","hablasteis","hablaron"],
    preteritoImperfecto:["hablaba","hablabas","hablaba","hablábamos","hablabais","hablaban"],
    presenteSubjuntivo:["hable","hables","hable","hablemos","habléis","hablen"],
    futuroStem:"hablar", note:"", mnemonic:"Fully regular — once you know the -ar pattern, every form here is predictable."},
  {inf:"comer", meaning:"to eat", level:1, pattern:"regular -er", affects:[],
    presente:["como","comes","come","comemos","coméis","comen"],
    preteritoIndefinido:["comí","comiste","comió","comimos","comisteis","comieron"],
    preteritoImperfecto:["comía","comías","comía","comíamos","comíais","comían"],
    presenteSubjuntivo:["coma","comas","coma","comamos","comáis","coman"],
    futuroStem:"comer", note:"", mnemonic:"Fully regular -er verb — the template for volver, aprender, beber, etc."},
  {inf:"vivir", meaning:"to live", level:1, pattern:"regular -ir", affects:[],
    presente:["vivo","vives","vive","vivimos","vivís","viven"],
    preteritoIndefinido:["viví","viviste","vivió","vivimos","vivisteis","vivieron"],
    preteritoImperfecto:["vivía","vivías","vivía","vivíamos","vivíais","vivían"],
    presenteSubjuntivo:["viva","vivas","viva","vivamos","viváis","vivan"],
    futuroStem:"vivir", note:"", mnemonic:"Fully regular -ir verb — identical endings to -er verbs except nosotros/vosotros in the present."},
  {inf:"estar", meaning:"to be (state/location)", level:1, pattern:"irregular",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["estoy","estás","está","estamos","estáis","están"],
    preteritoIndefinido:["estuve","estuviste","estuvo","estuvimos","estuvisteis","estuvieron"],
    preteritoImperfecto:["estaba","estabas","estaba","estábamos","estabais","estaban"],
    presenteSubjuntivo:["esté","estés","esté","estemos","estéis","estén"],
    futuroStem:"estar",
    note:"Estar marks temporary states or location. The present is stressed on the ending, not the stem, so tú/él/ellos carry an accent (estás, está, están). The preterite uses the irregular u-stem 'estuv-'.",
    mnemonic:"'estuv-' rhymes with 'tuv-' (tener) and 'anduv-' (andar) — group these three as the 'u-stem preterite family'."},
  {inf:"ser", meaning:"to be (identity)", level:1, pattern:"irregular",
    affects:["presente","preteritoIndefinido","preteritoImperfecto","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["soy","eres","es","somos","sois","son"],
    preteritoIndefinido:["fui","fuiste","fue","fuimos","fuisteis","fueron"],
    preteritoImperfecto:["era","eras","era","éramos","erais","eran"],
    presenteSubjuntivo:["sea","seas","sea","seamos","seáis","sean"],
    futuroStem:"ser",
    note:"Ser is one of the most irregular verbs in Spanish — nearly every tense has its own stem. Its preterite (fui, fuiste, fue...) is identical in form to the preterite of ir.",
    mnemonic:"Same trick as 'ir': in the past, 'fui' can mean 'I was' OR 'I went' — context decides which."},
  {inf:"tener", meaning:"to have", level:1, pattern:"irregular (go-verb, e→ie)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["tengo","tienes","tiene","tenemos","tenéis","tienen"],
    preteritoIndefinido:["tuve","tuviste","tuvo","tuvimos","tuvisteis","tuvieron"],
    preteritoImperfecto:["tenía","tenías","tenía","teníamos","teníais","tenían"],
    presenteSubjuntivo:["tenga","tengas","tenga","tengamos","tengáis","tengan"],
    futuroStem:"tendr",
    note:"'Tengo' is an irregular yo-form ('go-verb'). It also stem-changes e→ie in tú/él/ellos (tienes, tiene, tienen), skipping nosotros/vosotros — a 'boot' pattern. Future/conditional use the shortened stem 'tendr-'.",
    mnemonic:"Go-verbs: the irregular -go yo-form (tengo, pongo, salgo...) usually carries over into the present subjunctive stem (tenga, ponga, salga)."},
  {inf:"ir", meaning:"to go", level:2, pattern:"irregular",
    affects:["presente","preteritoIndefinido","preteritoImperfecto","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["voy","vas","va","vamos","vais","van"],
    preteritoIndefinido:["fui","fuiste","fue","fuimos","fuisteis","fueron"],
    preteritoImperfecto:["iba","ibas","iba","íbamos","ibais","iban"],
    presenteSubjuntivo:["vaya","vayas","vaya","vayamos","vayáis","vayan"],
    futuroStem:"ir",
    note:"Ir has its own stem in almost every tense (voy, iba, vaya...). Its preterite is borrowed from 'ser' — fui, fuiste, fue — so context tells you which verb is meant.",
    mnemonic:"'Voy, vas, va...' doesn't look like an -ir verb at all — just memorize it as a short, separate word each time."},
  {inf:"hacer", meaning:"to do / make", level:2, pattern:"irregular (go-verb)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo","futuro","condicional"],
    presente:["hago","haces","hace","hacemos","hacéis","hacen"],
    preteritoIndefinido:["hice","hiciste","hizo","hicimos","hicisteis","hicieron"],
    preteritoImperfecto:["hacía","hacías","hacía","hacíamos","hacíais","hacían"],
    presenteSubjuntivo:["haga","hagas","haga","hagamos","hagáis","hagan"],
    futuroStem:"har",
    note:"'Hago' is an irregular go-verb yo-form. In the preterite, the c→z shift in 'hizo' keeps the 'so' sound. Future/conditional shorten to the stem 'har-'.",
    mnemonic:"'Hizo' changes c→z only to keep the soft sound before 'o' — say it out loud, 'hico' would sound wrong."},
  {inf:"querer", meaning:"to want / love", level:2, pattern:"irregular (e→ie)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo","futuro","condicional"],
    presente:["quiero","quieres","quiere","queremos","queréis","quieren"],
    preteritoIndefinido:["quise","quisiste","quiso","quisimos","quisisteis","quisieron"],
    preteritoImperfecto:["quería","querías","quería","queríamos","queríais","querían"],
    presenteSubjuntivo:["quiera","quieras","quiera","queramos","queráis","quieran"],
    futuroStem:"querr",
    note:"Stem-changes e→ie in the present, but only outside nosotros/vosotros (the 'boot' shape). The preterite uses the irregular stem 'quis-', unrelated to the present stem.",
    mnemonic:"Preterite 'quise' can also mean 'I tried' in context — a subtle meaning shift native speakers use a lot."},
  {inf:"poder", meaning:"to be able to / can", level:2, pattern:"irregular (o→ue)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo","futuro","condicional"],
    presente:["puedo","puedes","puede","podemos","podéis","pueden"],
    preteritoIndefinido:["pude","pudiste","pudo","pudimos","pudisteis","pudieron"],
    preteritoImperfecto:["podía","podías","podía","podíamos","podíais","podían"],
    presenteSubjuntivo:["pueda","puedas","pueda","podamos","podáis","puedan"],
    futuroStem:"podr",
    note:"Boot-pattern o→ue stem change in the present. Preterite stem 'pud-' is irregular and unstressed endings (pude, pudiste...) carry no accent.",
    mnemonic:"'Pude' (no accent) = I managed to / I could (and did). Don't confuse with 'puede' (present, he/she can)."},
  {inf:"decir", meaning:"to say / tell", level:3, pattern:"irregular (e→i, go-verb)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo","futuro","condicional"],
    presente:["digo","dices","dice","decimos","decís","dicen"],
    preteritoIndefinido:["dije","dijiste","dijo","dijimos","dijisteis","dijeron"],
    preteritoImperfecto:["decía","decías","decía","decíamos","decíais","decían"],
    presenteSubjuntivo:["diga","digas","diga","digamos","digáis","digan"],
    futuroStem:"dir",
    note:"Go-verb yo-form (digo) plus e→i stem change. In the preterite, verbs whose stem ends in -j drop the 'i' in the ellos/ellas form: dijeron, not dijieron.",
    mnemonic:"j-stem preterites (dije, traje, condujeron) always take '-eron', never '-ieron' — a small but common spelling trap."},
  {inf:"poner", meaning:"to put", level:3, pattern:"irregular (go-verb)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo","futuro","condicional"],
    presente:["pongo","pones","pone","ponemos","ponéis","ponen"],
    preteritoIndefinido:["puse","pusiste","puso","pusimos","pusisteis","pusieron"],
    preteritoImperfecto:["ponía","ponías","ponía","poníamos","poníais","ponían"],
    presenteSubjuntivo:["ponga","pongas","ponga","pongamos","pongáis","pongan"],
    futuroStem:"pondr",
    note:"Go-verb (pongo) whose irregular -go carries into the subjunctive (ponga). Preterite stem 'pus-' is shared in spirit with poder's 'pud-' — both are u-stem preterites.",
    mnemonic:"Future stem inserts a 'd': pon- → pondr-, same pattern as tener → tendr- and venir → vendr-."},
  {inf:"venir", meaning:"to come", level:3, pattern:"irregular (e→ie, go-verb)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo","futuro","condicional"],
    presente:["vengo","vienes","viene","venimos","venís","vienen"],
    preteritoIndefinido:["vine","viniste","vino","vinimos","vinisteis","vinieron"],
    preteritoImperfecto:["venía","venías","venía","veníamos","veníais","venían"],
    presenteSubjuntivo:["venga","vengas","venga","vengamos","vengáis","vengan"],
    futuroStem:"vendr",
    note:"Same family as tener: go-verb yo-form plus e→ie boot pattern, and an inserted 'd' in the future stem (vendr-).",
    mnemonic:"Pair venir with tener mentally — vengo/tengo, viene/tiene, vendrá/tendrá all follow the same shape."},
  {inf:"pedir", meaning:"to ask for", level:3, pattern:"irregular (e→i)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["pido","pides","pide","pedimos","pedís","piden"],
    preteritoIndefinido:["pedí","pediste","pidió","pedimos","pedisteis","pidieron"],
    preteritoImperfecto:["pedía","pedías","pedía","pedíamos","pedíais","pedían"],
    presenteSubjuntivo:["pida","pidas","pida","pidamos","pidáis","pidan"],
    futuroStem:"pedir",
    note:"-ir stem-changing verb (e→i). Unlike -ar/-er stem changers, -ir verbs like this one ALSO change in the él/ellos preterite (pidió, pidieron) and throughout the subjunctive.",
    mnemonic:"-ir boot verbs 'leak' their stem change into the 3rd-person preterite — the one exception to 'imperfecto and preterite nosotros/vosotros stay regular'."},
  {inf:"volver", meaning:"to return", level:3, pattern:"irregular (o→ue)",
    affects:["presente","presenteSubjuntivo"],
    presente:["vuelvo","vuelves","vuelve","volvemos","volvéis","vuelven"],
    preteritoIndefinido:["volví","volviste","volvió","volvimos","volvisteis","volvieron"],
    preteritoImperfecto:["volvía","volvías","volvía","volvíamos","volvíais","volvían"],
    presenteSubjuntivo:["vuelva","vuelvas","vuelva","volvamos","volváis","vuelvan"],
    futuroStem:"volver",
    note:"Classic o→ue boot verb — regular everywhere except present tense and present subjunctive, and even there nosotros/vosotros stay unchanged.",
    mnemonic:"Say the four 'boot' forms out loud (vuelvo, vuelves, vuelve, vuelven) — they rhyme, and nosotros/vosotros break the rhyme on purpose."},
  {inf:"pensar", meaning:"to think", level:3, pattern:"irregular (e→ie)",
    affects:["presente","presenteSubjuntivo"],
    presente:["pienso","piensas","piensa","pensamos","pensáis","piensan"],
    preteritoIndefinido:["pensé","pensaste","pensó","pensamos","pensasteis","pensaron"],
    preteritoImperfecto:["pensaba","pensabas","pensaba","pensábamos","pensabais","pensaban"],
    presenteSubjuntivo:["piense","pienses","piense","pensemos","penséis","piensen"],
    futuroStem:"pensar",
    note:"-ar boot verb, e→ie. Fully regular in preterite and imperfect — the irregularity is confined to present tense and present subjunctive.",
    mnemonic:"'Pienso, luego existo' — the classic phrase is a free mnemonic for the yo-form pattern."},
  {inf:"saber", meaning:"to know (facts)", level:4, pattern:"irregular",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","futuro","condicional"],
    presente:["sé","sabes","sabe","sabemos","sabéis","saben"],
    preteritoIndefinido:["supe","supiste","supo","supimos","supisteis","supieron"],
    preteritoImperfecto:["sabía","sabías","sabía","sabíamos","sabíais","sabían"],
    presenteSubjuntivo:["sepa","sepas","sepa","sepamos","sepáis","sepan"],
    futuroStem:"sabr",
    note:"Irregular yo-form 'sé' (with accent, to distinguish it from 'se'). Preterite 'supe' often translates as 'I found out' rather than 'I knew'.",
    mnemonic:"Saber in the preterite = a moment of discovery ('supe la verdad' = I found out the truth), not an ongoing state."},
  {inf:"dar", meaning:"to give", level:4, pattern:"irregular",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["doy","das","da","damos","dais","dan"],
    preteritoIndefinido:["di","diste","dio","dimos","disteis","dieron"],
    preteritoImperfecto:["daba","dabas","daba","dábamos","dabais","daban"],
    presenteSubjuntivo:["dé","des","dé","demos","deis","den"],
    futuroStem:"dar",
    note:"Short irregular verb: 'doy' in the present, and an -er-style preterite (di, diste, dio) despite being an -ar verb. 'Dé' carries an accent only to distinguish it from the preposition 'de'.",
    mnemonic:"Dar 'borrows' -er/-ir preterite endings — pair it mentally with ver, which does the same thing."},
  {inf:"ver", meaning:"to see", level:4, pattern:"irregular",
    affects:["presente","preteritoImperfecto"],
    presente:["veo","ves","ve","vemos","veis","ven"],
    preteritoIndefinido:["vi","viste","vio","vimos","visteis","vieron"],
    preteritoImperfecto:["veía","veías","veía","veíamos","veíais","veían"],
    presenteSubjuntivo:["vea","veas","vea","veamos","veáis","vean"],
    futuroStem:"ver",
    note:"Present keeps the stem's 'e' (veo, not 'vo'). Preterite and imperfect are regular in shape but never take an accent on 'vi' / 'vio' because they're only one syllable.",
    mnemonic:"'Vi' and 'vio' have no accent — one-syllable preterite forms never need one, unlike 'dio' from dar (also no accent)."},
  {inf:"dormir", meaning:"to sleep", level:4, pattern:"irregular (o→ue/u)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["duermo","duermes","duerme","dormimos","dormís","duermen"],
    preteritoIndefinido:["dormí","dormiste","durmió","dormimos","dormisteis","durmieron"],
    preteritoImperfecto:["dormía","dormías","dormía","dormíamos","dormíais","dormían"],
    presenteSubjuntivo:["duerma","duermas","duerma","durmamos","durmáis","duerman"],
    futuroStem:"dormir",
    note:"Double stem change: o→ue in the present boot, but o→u (not ue) in the él/ellos preterite and throughout the subjunctive — durmió, durmieron, durmamos.",
    mnemonic:"Whenever an -ir o→ue verb needs a 3rd-person preterite or a nosotros/vosotros subjunctive, the 'ue' weakens to a plain 'u'."},
  {inf:"sentir", meaning:"to feel", level:4, pattern:"irregular (e→ie/i)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["siento","sientes","siente","sentimos","sentís","sienten"],
    preteritoIndefinido:["sentí","sentiste","sintió","sentimos","sentisteis","sintieron"],
    preteritoImperfecto:["sentía","sentías","sentía","sentíamos","sentíais","sentían"],
    presenteSubjuntivo:["sienta","sientas","sienta","sintamos","sintáis","sientan"],
    futuroStem:"sentir",
    note:"Same double-change family as dormir, but e→ie/i instead of o→ue/u: sintió, sintieron, sintamos.",
    mnemonic:"Group sentir, pedir and dormir as the three 'double stem-change' -ir verbs — same rule, different vowels."},
  {inf:"seguir", meaning:"to follow / continue", level:5, pattern:"irregular (e→i, spelling)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["sigo","sigues","sigue","seguimos","seguís","siguen"],
    preteritoIndefinido:["seguí","seguiste","siguió","seguimos","seguisteis","siguieron"],
    preteritoImperfecto:["seguía","seguías","seguía","seguíamos","seguíais","seguían"],
    presenteSubjuntivo:["siga","sigas","siga","sigamos","sigáis","sigan"],
    futuroStem:"seguir",
    note:"e→i stem change plus a spelling adjustment: 'gu' drops its 'u' before 'o'/'a' (sigo, not 'siguo') to keep the hard g sound.",
    mnemonic:"Spelling-only tweaks (gu→g before o/a, c→qu, g→gu, z→c) protect pronunciation — they're not real irregularities, just spelling rules."},
  {inf:"conocer", meaning:"to know (people/places)", level:5, pattern:"irregular (zco)",
    affects:["presente","presenteSubjuntivo"],
    presente:["conozco","conoces","conoce","conocemos","conocéis","conocen"],
    preteritoIndefinido:["conocí","conociste","conoció","conocimos","conocisteis","conocieron"],
    preteritoImperfecto:["conocía","conocías","conocía","conocíamos","conocíais","conocían"],
    presenteSubjuntivo:["conozca","conozcas","conozca","conozcamos","conozcáis","conozcan"],
    futuroStem:"conocer",
    note:"Verbs ending in a vowel + -cer/-cir insert a 'z' before the yo-form's 'c' (conozco), purely to keep the soft sound. That 'zc' carries through the whole subjunctive.",
    mnemonic:"Any -cer/-cir verb after a vowel (conocer, parecer, producir, conducir) takes -zco in yo — a whole family, not a one-off exception."},
  {inf:"traer", meaning:"to bring", level:5, pattern:"irregular",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["traigo","traes","trae","traemos","traéis","traen"],
    preteritoIndefinido:["traje","trajiste","trajo","trajimos","trajisteis","trajeron"],
    preteritoImperfecto:["traía","traías","traía","traíamos","traíais","traían"],
    presenteSubjuntivo:["traiga","traigas","traiga","traigamos","traigáis","traigan"],
    futuroStem:"traer",
    note:"Irregular yo-form 'traigo' (a 'go-verb' with an inserted i). Preterite stem 'traj-' is a j-stem, so the ellos form is 'trajeron', not 'trajieron'.",
    mnemonic:"Traer, decir and conducir all end their preterite stem in -j, and all drop the 'i' before '-eron'."},
  {inf:"oír", meaning:"to hear", level:5, pattern:"irregular (spelling y)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["oigo","oyes","oye","oímos","oís","oyen"],
    preteritoIndefinido:["oí","oíste","oyó","oímos","oísteis","oyeron"],
    preteritoImperfecto:["oía","oías","oía","oíamos","oíais","oían"],
    presenteSubjuntivo:["oiga","oigas","oiga","oigamos","oigáis","oigan"],
    futuroStem:"oír",
    note:"Between two vowels, an unstressed 'i' becomes 'y' for pronunciation (oye, oyó, oyeron) — a spelling rule, not a true stem change.",
    mnemonic:"Any verb with a vowel-i-vowel gap (oír, leer, construir) turns that 'i' into 'y' in the él/ellos preterite."},
  {inf:"jugar", meaning:"to play", level:6, pattern:"irregular (u→ue, spelling)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo"],
    presente:["juego","juegas","juega","jugamos","jugáis","juegan"],
    preteritoIndefinido:["jugué","jugaste","jugó","jugamos","jugasteis","jugaron"],
    preteritoImperfecto:["jugaba","jugabas","jugaba","jugábamos","jugabais","jugaban"],
    presenteSubjuntivo:["juegue","juegues","juegue","juguemos","juguéis","jueguen"],
    futuroStem:"jugar",
    note:"The only common u→ue boot verb. In the yo preterite and throughout the subjunctive, 'g' becomes 'gu' before 'e' to keep the hard g sound (jugué, juegue).",
    mnemonic:"g→gu before e, c→qu before e, z→c before e — the same spelling-protection rule shows up across dozens of verbs."},
  {inf:"construir", meaning:"to build", level:6, pattern:"irregular (spelling y)",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo"],
    presente:["construyo","construyes","construye","construimos","construís","construyen"],
    preteritoIndefinido:["construí","construiste","construyó","construimos","construisteis","construyeron"],
    preteritoImperfecto:["construía","construías","construía","construíamos","construíais","construían"],
    presenteSubjuntivo:["construya","construyas","construya","construyamos","construyáis","construyan"],
    futuroStem:"construir",
    note:"Verbs ending in -uir insert a 'y' whenever the stem's 'i' would otherwise be unstressed and next to another vowel — construyo, construyó, construyendo.",
    mnemonic:"Any -uir verb (construir, huir, incluir, destruir) behaves like oír's 'y' rule, just with a 'u' instead of a diphthong."},
  {inf:"leer", meaning:"to read", level:6, pattern:"irregular (spelling y)",
    affects:["preteritoIndefinido","imperfectoSubjuntivo"],
    presente:["leo","lees","lee","leemos","leéis","leen"],
    preteritoIndefinido:["leí","leíste","leyó","leímos","leísteis","leyeron"],
    preteritoImperfecto:["leía","leías","leía","leíamos","leíais","leían"],
    presenteSubjuntivo:["lea","leas","lea","leamos","leáis","lean"],
    futuroStem:"leer",
    note:"Present tense is fully regular. Only the él/ellos preterite is affected: the unstressed 'i' between vowels becomes 'y' (leyó, leyeron), same rule as oír and construir.",
    mnemonic:"If a regular -er/-ir verb's stem ends in a vowel (leer, creer, caer), expect a 'y' swap only in he/she and they preterite forms."},
  {inf:"haber", meaning:"to have (auxiliary) / there is-are", level:6, pattern:"irregular",
    affects:["presente","preteritoIndefinido","presenteSubjuntivo","imperfectoSubjuntivo","futuro","condicional"],
    presente:["he","has","ha","hemos","habéis","han"],
    preteritoIndefinido:["hube","hubiste","hubo","hubimos","hubisteis","hubieron"],
    preteritoImperfecto:["había","habías","había","habíamos","habíais","habían"],
    presenteSubjuntivo:["haya","hayas","haya","hayamos","hayáis","hayan"],
    futuroStem:"habr",
    note:"Mostly used as the auxiliary for compound tenses (he hablado = I have spoken) and impersonally as 'hay' (there is/are). Its own conjugations are fully irregular.",
    mnemonic:"'Hay' (there is/are) never changes for plural — 'hay un libro' and 'hay tres libros' both use 'hay', a very common learner slip."},
];


export {
  PERSONS, PRONOUN_WORD, TENSES, REGULAR_ENDINGS, FUTURO_END, CONDICIONAL_END,
  family, stem, TEMPLATES, VERBS
};
